# Generated by Django 5.0.4 on 2024-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='/home/dell/Desktop/socialmedia/media/posts/vit-c.jpg', max_length=200, null=True),
        ),
    ]
