# Generated by Django 5.0.4 on 2024-04-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='/home/dell/Desktop/socialmedia/media/posts/vit-c.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
